version: 2

models:
  - name: stg_salesforce__customers
    columns:
      - name: customer_id
        

  - name: stg_square__orders
    columns:
      - name: order_id


  - name: stg_salesforce__trucks
    columns:
      - name: truck_id

      - name: make